version: '3.3' # hellys

volumes:
  pg_data:
  media:
  static:
  docs:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  frontend:
    image: droj/foodgram_frontend
  #  build:
  #    context: ../frontend
  #    dockerfile: Dockerfile
    command: cp -r /app/build/. /frontend_static/
    volumes:
      # - ../frontend/:/app/result_build/
      - static:/frontend_static
  backend:
    image: droj/foodgram_backend
  #  build: ../backend/
    env_file: .env
    volumes:
      - media:/app/media/
      - static:/backend_static
      - docs:/docs
  nginx:
  #  image: nginx:1.19.3
    image: droj/foodgram_gateway
    ports:
      - "8000:80"
    volumes:
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      # - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/media/
      - static:/staticfiles/
      - docs:/docs/
