version: '3.3'

volumes:
  pg_data:
  media:
  static:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: droj/foodgram_backend
    env_file: .env
    volumes:
      - media:/app/media/
      - static:/backend_static
    depends_on:
      - db

  frontend:
    image: droj/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  nginx:
    image: droj/foodgram_gateway
    ports:
      - "8000:80"
    volumes:
      - media:/media/
      - static:/staticfiles/
    depends_on:
      - frontend
